name: Flask CI

on:
  push:
    branches: ["main", "Flask"]
    paths:
      - "flask-app/**"
      - ".github/workflows/flask-ci.yml"
  workflow_dispatch: {}

jobs:
  build-and-push-flask:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Flask image
        uses: docker/build-push-action@v6
        with:
          context: ./flask-app
          file: ./flask-app/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/flask-image-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/flask-image-service:${{ github.sha }}
